# Generated by Django 5.2.1 on 2025-06-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Represents a database migration for creating the `Note` model.

    This migration sets up the `Note` model in the database
    with fields for `id`, `title`, `content`, and `created_at`. It is
    designed to define the schema for the `Note` entity and ensure the
    database structure matches the application's
    requirements.

    :ivar initial: Specifies whether this is the initial migration
    for the relatedapplication.
    :type initial: bool
    :ivar dependencies: A list of other migrations that this
    migration depends on.
    :type dependencies: list
    :ivar operations: A list of operations to be applied
    for this migration,
        including the creation of the `Note` model.
    :type operations: list
    """
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
